name: Continuous Integration Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install ESLint
        run: npm install eslint

      - name: Run Linter
        run: npx eslint . || true